import http from 'node:http';
import {readFile,writeFile,mkdir,unlink} from 'node:fs/promises';
import path from 'node:path';
import {createHash,randomBytes} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {config} from './config.mjs';import {openDB,migrate} from './db.mjs';
import {AppError,id,text,date,deadlines,requireManager,audit,createTender,reviewTender,updateTask} from './domain.mjs';
import {KEYWORDS} from './matching.mjs';import {enqueueScan,startJobs} from './jobs.mjs';import {seed} from './manage.mjs';
const hash=s=>createHash('sha256').update(s).digest('hex');
async function body(req,max=200000){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>max)throw new AppError(413,'Request exceeds size limit');chunks.push(chunk);}return Buffer.concat(chunks);}
async function json(req){try{return JSON.parse((await body(req)).toString()||'{}');}catch(e){if(e instanceof AppError)throw e;throw new AppError(400,'Invalid JSON');}}
function uploadName(req){try{return text(decodeURIComponent(req.headers['x-file-name']||''),'File name',200);}catch{throw new AppError(400,'Provide a valid encoded file name.');}}
function send(res,code,data){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));}
export function makeServer(db,c){
 const files=path.join(c.data,'documents');
 async function session(req){const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('psa_session='))?.slice(12);if(!token)return null;return db.one('SELECT u.id,u.email,u.name,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>NOW() AND u.active=TRUE',[hash(token)]);}
 async function login(res,userId){const token=randomBytes(32).toString('hex');await db.query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '8 hours')",[hash(token),userId]);res.setHeader('Set-Cookie',`psa_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${c.mode==='live'?'; Secure':''}`);}
 async function rate(key,max){const r=await db.one("INSERT INTO rate_limits(key,attempts) VALUES($1,1) ON CONFLICT(key) DO UPDATE SET attempts=CASE WHEN rate_limits.window_at<NOW()-INTERVAL '1 minute' THEN 1 ELSE rate_limits.attempts+1 END,window_at=CASE WHEN rate_limits.window_at<NOW()-INTERVAL '1 minute' THEN NOW() ELSE rate_limits.window_at END RETURNING attempts",[key]);if(r.attempts>max)throw new AppError(429,'Too many requests. Try again in a minute.');}
 return http.createServer(async(req,res)=>{
  res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
  try{
   const url=new URL(req.url,c.origin),route=url.pathname,method=req.method;
   if(c.mode==='demo'&&!['localhost','127.0.0.1','[::1]'].includes(new URL('http://'+req.headers.host).hostname))throw new AppError(403,'Demo access is local only.');
   if(!['GET','HEAD'].includes(method)&&req.headers.origin!==new URL(c.origin).origin)throw new AppError(403,'Request origin is not allowed.');
   if(route==='/health'){return send(res,200,{ok:true,mode:c.mode});}
   if(route==='/api/config'&&method==='GET')return send(res,200,{mode:c.mode,emailMode:c.emailMode,companyDomain:c.domain,schedule:'Daily at 08:00 CAT (06:00 UTC)',users:c.mode==='demo'?await db.all('SELECT id,name,role FROM users WHERE active=TRUE'):[]});
   if(route==='/api/auth/demo'&&method==='POST'){if(c.mode!=='demo')throw new AppError(404,'Not found');const input=await json(req);if(!await db.one('SELECT id FROM users WHERE id=$1 AND active=TRUE',[input.user_id]))throw new AppError(400,'Invalid demo user');await login(res,input.user_id);return send(res,200,{ok:true});}
   if(route==='/api/auth/request'&&method==='POST'){
    await rate('login-ip:'+req.socket.remoteAddress,10);const input=await json(req);const email=String(input.email||'').toLowerCase().trim();await rate('login-email:'+hash(email),3);
    if(c.mode!=='live')throw new AppError(400,'Use the local demo sign-in.');
    const user=email.endsWith('@'+c.domain)?await db.one('SELECT id FROM users WHERE email=$1 AND active=TRUE',[email]):null;
    if(user){const token=randomBytes(32).toString('hex');await db.transaction(async tx=>{await tx.query('DELETE FROM login_tokens WHERE user_id=$1',[user.id]);await tx.query("INSERT INTO login_tokens(token_hash,user_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '15 minutes')",[hash(token),user.id]);await tx.query("INSERT INTO notifications(id,dedupe_key,kind,recipient_id,subject,body) VALUES($1,$2,'login',$3,'Your tender workspace sign-in link',$4)",[id(),id(),user.id,`Sign in within 15 minutes: ${c.origin}/#login=${token}\nThis link can be used once.`]);});}
    return send(res,200,{message:'If this is an active registered company account, a sign-in link will arrive shortly.'});
   }
   if(route==='/api/auth/consume'&&method==='POST'){await rate('consume:'+req.socket.remoteAddress,10);const input=await json(req);const token=await db.one('DELETE FROM login_tokens WHERE token_hash=$1 AND expires_at>NOW() RETURNING user_id',[hash(String(input.token||''))]);if(!token)throw new AppError(401,'The sign-in link is expired or already used.');if(!await db.one('SELECT id FROM users WHERE id=$1 AND active=TRUE',[token.user_id]))throw new AppError(401,'Account unavailable');await login(res,token.user_id);return send(res,200,{ok:true});}
   const user=await session(req);
   if(route.startsWith('/api/')&&!user)throw new AppError(401,'Sign in to continue.');
   if(route==='/api/me')return send(res,200,user);
   if(route==='/api/auth/logout'&&method==='POST'){const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('psa_session='))?.slice(12);if(token)await db.query('DELETE FROM sessions WHERE token_hash=$1',[hash(token)]);res.setHeader('Set-Cookie','psa_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return send(res,200,{ok:true});}
   if(route==='/api/users'&&method==='GET')return send(res,200,await db.all('SELECT id,name,role FROM users WHERE active=TRUE ORDER BY name'));
   if(route==='/api/keywords')return send(res,200,{groups:KEYWORDS,thresholds:{strong:70,moderate:40},rule:'Title: phrase 45 / keyword 30; scope: procurement sentence 35 / mention 20; groups: two 10 / three or more 20.'});
   if(route==='/api/tenders'&&method==='GET')return send(res,200,await db.all('SELECT t.*,u.name AS owner_name FROM tenders t LEFT JOIN users u ON u.id=t.owner_id ORDER BY t.score DESC,t.created_at DESC LIMIT 1000'));
   if(route==='/api/tenders'&&method==='POST')return send(res,201,await createTender(db,user,await json(req)));
   let match=route.match(/^\/api\/tenders\/([^/]+)$/);
   if(match&&method==='GET'){const t=await db.one('SELECT t.*,u.name AS owner_name FROM tenders t LEFT JOIN users u ON u.id=t.owner_id WHERE t.id=$1',[match[1]]);if(!t)throw new AppError(404,'Tender not found.');return send(res,200,{...t,tasks:await db.all('SELECT * FROM tasks WHERE tender_id=$1 ORDER BY created_at',[t.id]),sources:await db.all('SELECT * FROM tender_sources WHERE tender_id=$1',[t.id]),documents:await db.all('SELECT id,name,size,created_at FROM documents WHERE tender_id=$1',[t.id]),history:await db.all('SELECT a.*,u.name AS actor FROM audit a LEFT JOIN users u ON u.id=a.actor_id WHERE tender_id=$1 ORDER BY created_at DESC LIMIT 100',[t.id])});}
   match=route.match(/^\/api\/tenders\/([^/]+)\/review$/);if(match&&method==='POST')return send(res,200,await reviewTender(db,user,match[1],await json(req)));
   match=route.match(/^\/api\/tasks\/([^/]+)$/);if(match&&method==='PATCH')return send(res,200,await updateTask(db,user,match[1],await json(req)));
   match=route.match(/^\/api\/tenders\/([^/]+)\/deadline$/);
   if(match&&method==='POST'){requireManager(user);const input=await json(req),closing=date(input.closing_at),internal=date(input.internal_at);if(!closing)throw new AppError(400,'Confirm a closing time.');await db.transaction(async tx=>{const t=await tx.one('SELECT * FROM tenders WHERE id=$1 FOR UPDATE',[match[1]]);if(!t)throw new AppError(404,'Tender not found.');deadlines(closing,internal,t.stage);await tx.query("UPDATE tenders SET closing_at=$2,internal_at=$3,deadline_version=deadline_version+1,verification='staff-confirmed',proposal_pending=FALSE,proposed_closing=NULL,updated_at=NOW() WHERE id=$1",[t.id,closing,internal]);await tx.query('UPDATE tasks SET due_at=$2 WHERE tender_id=$1 AND done=FALSE',[t.id,internal]);await tx.query("UPDATE notifications SET status='cancelled' WHERE tender_id=$1 AND kind IN ('deadline','escalation') AND status IN ('pending','preview')",[t.id]);await audit(tx,t.id,user.id,'deadline_confirmed',{previous:t.closing_at,closing});if(t.owner_id)await tx.query("INSERT INTO notifications(id,dedupe_key,kind,recipient_id,tender_id,subject,body) VALUES($1,$2,'amendment',$3,$4,$5,$6)",[id(),id(),t.owner_id,t.id,`Confirmed deadline change: ${t.title}`,`Closing: ${closing}\n${c.origin}/?tender=${t.id}`]);});return send(res,200,{ok:true});}
   match=route.match(/^\/api\/tenders\/([^/]+)\/stage$/);
   if(match&&method==='POST'){const input=await json(req);if(!['reviewing','preparing','approval','submitted','won','lost'].includes(input.stage))throw new AppError(400,'Invalid stage');await db.transaction(async tx=>{const t=await tx.one('SELECT * FROM tenders WHERE id=$1 FOR UPDATE',[match[1]]);if(!t)throw new AppError(404,'Tender not found');if(user.role!=='manager'&&user.id!==t.owner_id)throw new AppError(403,'Only the owner or Projects Manager can change the stage.');deadlines(t.closing_at,t.internal_at,input.stage);if(['won','lost'].includes(input.stage)&&!t.submitted_at)throw new AppError(400,'Record submission before the outcome.');const receipt=input.stage==='submitted'?text(input.submission_reference,'Submission receipt/reference',1000):t.submission_reference;await tx.query('UPDATE tenders SET stage=$2,submission_reference=$3,submitted_at=$4,updated_at=NOW() WHERE id=$1',[t.id,input.stage,receipt,input.stage==='submitted'?new Date():t.submitted_at]);if(['submitted','won','lost'].includes(input.stage))await tx.query("UPDATE notifications SET status='cancelled' WHERE tender_id=$1 AND kind IN ('deadline','escalation') AND status IN ('pending','preview')",[t.id]);await audit(tx,t.id,user.id,'stage_changed',{stage:input.stage,receipt});});return send(res,200,{ok:true});}
   match=route.match(/^\/api\/tenders\/([^/]+)\/owner$/);
   if(match&&method==='POST'){const input=await json(req);await db.transaction(async tx=>{const t=await tx.one('SELECT * FROM tenders WHERE id=$1 FOR UPDATE',[match[1]]);if(!t)throw new AppError(404,'Tender not found');if(user.role!=='manager'&&user.id!==t.owner_id)throw new AppError(403,'Only the current owner or Projects Manager can reassign this tender.');if(!await tx.one('SELECT id FROM users WHERE id=$1 AND active=TRUE',[input.owner_id]))throw new AppError(400,'Choose an active staff owner.');await tx.query('UPDATE tenders SET owner_id=$2,updated_at=NOW() WHERE id=$1',[t.id,input.owner_id]);await tx.query('UPDATE tasks SET assignee_id=$2 WHERE tender_id=$1 AND done=FALSE AND assignee_id=$3',[t.id,input.owner_id,t.owner_id]);await audit(tx,t.id,user.id,'owner_changed',{previous:t.owner_id,owner:input.owner_id});});return send(res,200,{ok:true});}
   match=route.match(/^\/api\/tenders\/([^/]+)\/comments$/);
   if(match&&method==='POST'){const input=await json(req);const comment=text(input.comment,'Comment',4000);if(!await db.one('SELECT id FROM tenders WHERE id=$1',[match[1]]))throw new AppError(404,'Tender not found');await audit(db,match[1],user.id,'comment',{comment});return send(res,201,{ok:true});}
   match=route.match(/^\/api\/tenders\/([^/]+)\/documents$/);
   if(match&&method==='POST'){if(!await db.one('SELECT id FROM tenders WHERE id=$1',[match[1]]))throw new AppError(404,'Tender not found');const name=uploadName(req);const raw=await body(req,10*1024*1024);if(!raw.length)throw new AppError(400,'Empty file');const did=id();await mkdir(files,{recursive:true});await writeFile(path.join(files,did),raw,{flag:'wx'});try{await db.transaction(async tx=>{await tx.query('INSERT INTO documents(id,tender_id,name,content_type,size,storage_key,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[did,match[1],path.basename(name),'application/octet-stream',raw.length,did,user.id]);await audit(tx,match[1],user.id,'document_uploaded',{name});});}catch(e){await unlink(path.join(files,did));throw e;}return send(res,201,{id:did});}
   match=route.match(/^\/api\/documents\/([^/]+)$/);if(match&&method==='GET'){const d=await db.one('SELECT * FROM documents WHERE id=$1',[match[1]]);if(!d)throw new AppError(404,'File not found');const data=await readFile(path.join(files,d.storage_key));res.writeHead(200,{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(d.name)}`});return res.end(data);}
   if(route==='/api/scans'&&method==='POST'){await rate('scan:'+user.id,2);return send(res,202,await enqueueScan(db,user.id));}
   if(route==='/api/scans'&&method==='GET')return send(res,200,await db.all('SELECT id,status,result,created_at,finished_at,attempts FROM scan_jobs ORDER BY created_at DESC LIMIT 30'));
   if(route==='/api/sources')return send(res,200,await db.all('SELECT * FROM sources ORDER BY name'));
   if(route==='/api/notifications'){return send(res,200,await db.all("SELECT n.id,n.kind,n.subject,n.body,n.status,n.attempts,n.last_error,n.created_at,u.name AS recipient FROM notifications n JOIN users u ON u.id=n.recipient_id WHERE n.kind<>'login' AND (n.recipient_id=$1 OR $2=TRUE) ORDER BY n.created_at DESC LIMIT 100",[user.id,['manager','admin'].includes(user.role)]));}
   if(route==='/api/ai/status')return send(res,200,{status:'unconfigured',message:'AI extraction is not connected. Keyword scores are deterministic; tender text and supporting passages are available.'});
   const staticFiles={'/':'index.html','/app.js':'app.js','/style.css':'style.css'};
   if(method==='GET'&&staticFiles[route]){const name=staticFiles[route];res.writeHead(200,{'Content-Type':name.endsWith('.js')?'text/javascript; charset=utf-8':name.endsWith('.css')?'text/css; charset=utf-8':'text/html; charset=utf-8'});return res.end(await readFile(new URL('../public/'+name,import.meta.url)));}
   throw new AppError(404,'Not found');
  }catch(e){if(e.code==='23505')return send(res,409,{error:'A matching record already exists. Refresh and open the existing record.'});if(e.code==='23503')return send(res,400,{error:'Referenced record is unavailable.'});if(!(e instanceof AppError))console.error('Request failed:',e.message);send(res,e.status||500,{error:e.status?e.message:'The operation failed. Your data was not silently discarded; please retry.'});}
 });
}
if(process.argv[1]&&fileURLToPath(import.meta.url)===path.resolve(process.argv[1])){
 const c=config(),db=await openDB(c);await migrate(db);if(c.mode==='demo')await seed(db,c);
 const server=makeServer(db,c);const jobs=!c.database?startJobs(db,c):null;
 server.listen(c.port,c.host,()=>console.log(`Tender workspace: ${c.origin}\nMode: ${c.mode}; email: ${c.emailMode}; ${jobs?'embedded worker':'start npm run worker separately'}.`));
 const stop=()=>{jobs?.stop();server.close(async()=>{await db.close();process.exit(0);});};process.on('SIGINT',stop);process.on('SIGTERM',stop);
}
